sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "l+RVnUiHxkJVpv20TpMxaE6j/wsdi179sIejt6Ut6XeFlT5WCCTt2VaAKsazRnE8ZGYbwmRtMG425rsRnIhdR5aay0e3BNXROTzgf06PLq2AakekpgR77H1tN9gKEfPvax2wXnRqcTzKvrYAuMk+aTAEdzwH+3cjPPQj2wb34QeePtthHm0MUC7Lg/qjfLxOpllwN3YNZp4Y8abWH7sxKPBBtOjGcwOMx9TPwRAihwt6RyLXDxpajjHsrMeBRhp8VnHX7hB/HxSRn5i3yjoHffJL9JuXwN4E9MQhrmloNRuRzdkdfVr8xmI+kR2i9xGT7sNsD1P1Orygy5D6zmQ/XLz9FU2o/h8DytBWRbrXBQLrx3fVhuwdf/UR290BG3AN05gOpYLNn0Px+SyoB8ZqF3iXbTfAEtwF1tQAEjTfz2M5jJfbKU8nKjJ68T/9Z6CGsQIRHWwpYH9Kt+s3SVDrCs0Okau3n55zBS+7c8z3bQdPWBtRgu+Jyee1iZRY/w/DtF6sf/4pQQLRXzFBwDRqeA80SShTGZcCfagOZdZAibSMcTuqxnx1gtT+S2+zczaOqa09xX3ZmlhUs5VK5F8x5hwyt3JCoOpwvQ1tyyKXCkGZLRe028Dt5Y9/u7fU3vahTTMYwREsmI1pupG1cnbrfzm2hQznWumi6DlPrCgUsG0="
  - secure: "U4PBBCYQ2HR2lCuN0xfxUww6WTKizRJ8wWpeGhwWiGQ/zsgAZ2gjMX0sguIPSJgkcdSA0uo8zANFLaeSbbPfZicpc0Bh5XeY9syB61pVcwjVCf2LpJtwG4sPzxDRMGrtD2FlPzC8b7axBHQOl28fPcfEQs16Z5R3Cr8cGy0AHbt1xVeDD/TRSQ6PsAoLh/XolTcsQ78/4vgUU/BKLX/UEmt9O7GngXKVOFJlu8BRRVXxUrWLkqY1uTDmuJnhO6D4ZgaZSgHFHRC0yTdEZqK3cpNkQ153SGLqEDkeGSkK3oH7hKBIT0tszb5hIpKkB5kY+9hxiJCWvImep4R0UCvhU0vCsiMGO/KWcinD+T+8bBu0VYPvLjWDE7ugIS81eOwM0nY0Gi8jqNTDHMVhJJpFFrpRc3KtBE3JLMnIAkr0KxLTh2gEPFM6iEkI84rNBqzdzCrZUVOVYupCm/VGJ0BEHBqcHKoH7Gx5F8BrgEkT1JPi4/p6Z49OyOqrWEtQjA7znIQhW+Y4lPfLOp4taDFh9yYrqzdLIAWtIWAblSQ7xFwxUuNa6/T1YB3bWTBRsO6+TuAywkd68QT01Jp+PYEGsw03r+jTrkx0HlL1ly6lgYk+Vhd8Ij6GetIUtQQvQqy7zlq7tnpHtOu1HZ7zUFZ03vMZDhADctXPsHrmDULbpkg="
  - secure: "OgyCcAsecIVvvmkO6cRXrEw30cRZhmSAUPFvWTwcO+q9KRicJy063GN2RP+T4CW77Ar0G8cHwnXP+abIDuinFE/OLe60HgLmtZcfrG8LJGq6vp1ebkYTa8wmN48DCXwbF00YTavMsOmWc9hjY2CdlvLEaEjTvsFJN9qxLsS0NVrZ5yxNT7j9VoGO+bRFj+LAkmdO+/3+rAGJrQ2sf4/82zjgWKKDjFAhlQCJdEM+H1LNx7tDZixVlim23++SxBq5UnsJRU0NDVRXVMOqaweSO4RvzjUenZtImpN7v2rcbOivPYbRRVo2S3hw/4bFI56PLGPU8MuzrObutWjNBdDziA+0xe8I3/oUj6tFXIo9PceTdtfmqOZuyXMBkk5DaLf0nmFoBcI7EeFIqW8/Bejq9O4h/tfPxZN9/bfocFE4xrPYR82UaTRVucmeDR0GNS6rNGc+iSu9xP6l7tTZEs7XCv8UKL7QTna7I9YuF+Msn4mwwylr/cmqXcwDYDInmawPgF8mysjcwDU+Gncwu7ud2Ruvi3dUyemTOLQBrkFniaX34eXi47z2OluAobUauCpg42r9rRbMwQ5b8nS7gkrgnCvRc1ehyQ+nA4shg/yhdoZJamedW4YjgpYgGOMCqrtCkFCFR9pQJjrMxrfbxlBNb7IQFiu17aClQy9TQ+gWzYg="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
